version: '3.8'

services:
  claims-orchestrator:
    build: ./services/claims-orchestrator
    ports:
      - "8000:8000"
    environment:
      - SERVICE_NAME=claims-orchestrator
      - ORCH_VERIFICATION_URL=http://verification-service:8000
      - ORCH_VALUATION_URL=http://valuation-service:8000
      - ORCH_PAYMENT_URL=http://payment-service:8000
      - ORCH_AUDIT_URL=http://audit-service:8000
      - ORCH_VIN_URL=http://vin-monitor:8000
    depends_on:
      - verification-service
      - valuation-service
      - payment-service
      - audit-service
      - vin-monitor
    networks:
      - vvp-network

  verification-service:
    build: ./services/verification-service
    environment:
      - SERVICE_NAME=verification-service
    networks:
      - vvp-network

  valuation-service:
    build: ./services/valuation-service
    environment:
      - SERVICE_NAME=valuation-service
    networks:
      - vvp-network

  payment-service:
    build: ./services/payment-service
    environment:
      - SERVICE_NAME=payment-service
    networks:
      - vvp-network

  vin-monitor:
    build: ./services/vin-monitor
    environment:
      - SERVICE_NAME=vin-monitor
    networks:
      - vvp-network

  audit-service:
    build: ./services/audit-service
    environment:
      - SERVICE_NAME=audit-service
    networks:
      - vvp-network

  web-ui:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./web-ui:/usr/share/nginx/html:ro
      - ./web-ui/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - claims-orchestrator
    networks:
      - vvp-network

networks:
  vvp-network:
    driver: bridge

volumes:
  audit-data:
